"""add_product_name

Revision ID: 54c6612ca1a4
Revises: 6f4e4eedc4bb
Create Date: 2024-06-21 16:49:57.398650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c6612ca1a4'
down_revision = '6f4e4eedc4bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
