"""'create_sale_log_table'

Revision ID: 6f4e4eedc4bb
Revises: 6cd07bb757a2
Create Date: 2024-06-21 10:07:10.625898

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6f4e4eedc4bb"
down_revision = "6cd07bb757a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sale_log",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("quantity_sold", sa.Integer(), nullable=False),
        sa.Column("product_sold", sa.String(), nullable=False),
        sa.Column(
            "time_of_sale",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_sold"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sale_log")
    # ### end Alembic commands ###
