"""initial_migration

Revision ID: 70ea070ea924
Revises: 
Create Date: 2024-06-17 17:42:02.116957

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "70ea070ea924"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "laboratory",
        sa.Column("cnpj", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("cnpj"),
    )
    op.create_table(
        "substance",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "product",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("substance_name", sa.String(), nullable=False),
        sa.Column("laboratory_cnpj", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["laboratory_cnpj"],
            ["laboratory.cnpj"],
        ),
        sa.ForeignKeyConstraint(
            ["substance_name"],
            ["substance.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product")
    op.drop_table("substance")
    op.drop_table("laboratory")
    # ### end Alembic commands ###
