version: '3.9'

services:
  postgres-db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    ports:
      - 5432:5432  
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: postgres_db
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
